on:
  workflow_dispatch:

jobs:
  DocTide_job:
    runs-on: ubuntu-latest
    name: Run Doctide
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: run DocTide action
        id: doctide
        uses: BrandtBoys/Bachelor@v9
        with:
          testing: true