on:
  push:

jobs:
  DocTide_job:
    runs-on: ubuntu-latest
    name: Run Doctide
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: DocTide Action
        uses: BrandtBoys/DocTide@vmain
        with:
          testing: false
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
